### ISSUE TITLE
It just works

### ISSUE THREAD

**Issue by Ypot** [Aightech/org-gantt-svg#1]
Out of the box, working. Incredible, thanks. (Windows 10).

Why it doesn't use deadlines? I suppose it is meditated.

**Comment by Aightech** [comment]
Thank you !

I used time ranges because I thought it was more meaningful and to let the possibility to add some graphical signal for deadline in the Gantt chart. But I realised after that most of the emacs project schedules and deadlines were used as ranges and also that the keybinding is easier to use. So I  have committed a change to generate the Gantt chart from schedule and deadline.

**Comment by Ypot** [comment]
> 
> 
> Thank you !
> 
> I used time ranges because I thought it was more meaningful and to let the possibility to add some graphical signal for deadline in the Gantt chart. But I realised after that most of the emacs project schedules and deadlines were used as ranges and also that the keybinding is easier to use. So I have committed a change to generate the Gantt chart from schedule and deadline.

Hi
I didn't know how to install the package, so I waited because I thought you were going to upload it. But I can't yet find the package. Could you give some install instructions?
Thanks :-)
